---
title: "PATRIC Simulation Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(htmltools))


ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text = element_text(size = 10))
ggplot2::theme_update(legend.position = "top")
# ggplot2::theme_update(legend.title = element_blank())
ggplot2::theme_update(axis.text.x = element_text(size = 10))
ggplot2::theme_update(axis.text.y = element_text(size = 10))

```

```{r, include=FALSE}
nres <- 2

dsup <- data.frame()
dni <- data.frame()

fout <- list.files("out")

for(i in 1:nres){
  l <- readRDS(paste0("out/", fout[i]))
  
  # superiority data
  # test whether max is superior to all other doses
  dtmp <- cbind(l$dsup, apply(l$dsup[, 1:ncol(l$dsup)], 2, function(x){ x > 0.9}))
  
  tmp <- c(scenario = l$scenario, 
           range = l$trtgrps$p_range,
           n_per_trt = l$n_per_trt,
           colMeans(dtmp[, 11:ncol(dtmp)]))
  
  # eta columns are the proportion of times that the proportion that recovered on max
  # duration was greater than the proportion recovered on the 1 day, 2 days, 3 days etc
  dsup <- rbind(dsup, tmp)
  
  names(dsup) <- names(tmp)
  
  # non-inferiority
  dtmp <- cbind(l$dni, apply(l$dni[, 1:ncol(l$dni)], 2, function(x){ x > 0.9}))
  
  tmp <- c(scenario = l$scenario, 
           range = l$trtgrps$p_range,
           n_per_trt = l$n_per_trt,
           colMeans(dtmp[, 11:ncol(dtmp)]))
  
  # eta columns are the proportion of times that the proportion that recovered on max
  # duration was non-inferior to the proportion recovered on the 1 day, 2 days, 3 days etc
  dni <- rbind(dni, tmp)
  
  names(dni) <- names(tmp)
  
}

rownames(dsup) <- NULL
rownames(dni) <- NULL



```


## Superiority

eta columns are the proportion of times that the proportion that recovered on max duration was greater than the proportion recovered on the 1 day, 2 days, 3 days etc.

```{r, echo = F, eval = T}
digits <- c(0, 1, 0, 
            2, 2, 2, 2, 2, 
            2, 2, 2, 2, 2
            )

kable(dni,
      caption = paste0("Table. Simulation Results (", nrow(dsup), " rows)"),
      col.names = c("Scenario", "Range", "n_per_arm", 
                    paste0("d_max vs ", 0:9)),
      digits = digits) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left",
                font_size = 12,
                latex_options = "hold_position") 

```

## Non-inferiority

eta columns are the proportion of times that the proportion that recovered on max duration was non-inferior to the proportion recovered on the 1 day, 2 days, 3 days etc

```{r, echo = F, eval = T}
digits <- c(0, 1, 0, 
            2, 2, 2, 2, 2, 
            2, 2, 2, 2, 2
            )

kable(dsup,
      caption = paste0("Table. Simulation Results (", nrow(dsup), " rows)"),
      col.names = c("Scenario", "Range", "n_per_arm", 
                    paste0("d_max vs ", 0:9)),
      digits = digits) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left",
                font_size = 12,
                latex_options = "hold_position") 

```


## Todo

